version: "3.9"

services:
  hrmanager: 
    build:
      context: .
      dockerfile: Nsu.Contest.Web.HRManager/Dockerfile
    command: dotnet run
    networks:
      - employees-hrmanager-network
    ports:
      - "5000:80"

  # hrdirector: 
  #   build: Nsu.Contest.Web.HRDirector/
  #   command: dotnet run

  employee:
    build:
      context: .
      dockerfile: Nsu.Contest.Web.Employee/Dockerfile
    command: dotnet run
    depends_on:
      - hrmanager
    networks:
      - employees-hrmanager-network

  junior-1:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 1
        EmployeeServiceOptions__EmployeeType: junior

  junior-2:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 2
        EmployeeServiceOptions__EmployeeType: junior

  junior-3:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 3
        EmployeeServiceOptions__EmployeeType: junior

  junior-4:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 4
        EmployeeServiceOptions__EmployeeType: junior

  junior-5:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 5
        EmployeeServiceOptions__EmployeeType: junior

  teamlead-1:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 6
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-2:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 7
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-3:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 8
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-4:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 9
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-5:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 10
        EmployeeServiceOptions__EmployeeType: teamlead

networks: 
  # Как ограничить сетевое взаимодействие таким образом, 
  # чтобы каждый employee мог общаться только с hrmanager, 
  # а контейнеры employee не могли взаимодействовать между собой?
  # Можно настроить отдельные сети для каждого employee и hrmanager, а красивее можно?
  employees-hrmanager-network:
    driver: brEmployeeServiceOptions__EmployeeIdge
