version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - contest_network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 100

  postgres-hrmanager:
    image: postgres:15
    environment:
      POSTGRES_USER: hrmanager
      POSTGRES_PASSWORD: hrmanager
      POSTGRES_DB: hrmanager_db
    networks:
      - contest_network
    ports:
      - "5001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrmanager -d hrmanager_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  migration-hrmanager:
    build:
      context: .
      dockerfile: Dockerfile.migration
    entrypoint: ["/usr/local/bin/migrate.sh", "Nsu.Contest.Web.HRManager"]
    depends_on:
      postgres-hrmanager:
        condition: service_healthy
    networks:
      - contest_network
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh Nsu.Contest.Web.HRManager"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  hrmanager: 
    build:
      context: .
      dockerfile: Nsu.Contest.Web.HRManager/Dockerfile
    depends_on:
      hrdirector:
        condition: service_healthy
      postgres-hrmanager:
        condition: service_healthy
      migration-hrmanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - contest_network
    ports:
      - "5000:80"
    healthcheck:
      test: "curl hrmanager:80"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  postgres-hrdirector:
    image: postgres:15
    environment:
      POSTGRES_USER: hrdirector
      POSTGRES_PASSWORD: hrdirector
      POSTGRES_DB: hrdirector_db
    networks:
      - contest_network
    ports:
      - "6001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hrdirector -d hrdirector_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  migration-hrdirector:
    build:
      context: .
      dockerfile: Dockerfile.migration
    entrypoint: ["/usr/local/bin/migrate.sh", "Nsu.Contest.Web.HRDirector"]
    depends_on:
      postgres-hrdirector:
        condition: service_healthy
    networks:
      - contest_network
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh Nsu.Contest.Web.HRDirector"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  hrdirector: 
    build:
      context: .
      dockerfile: Nsu.Contest.Web.HRManager/Dockerfile
    depends_on:
      postgres-hrdirector:
        condition: service_healthy
      migration-hrdirector:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - contest_network
    ports:
      - "6000:80"
    healthcheck:
      test: "curl hrdirector:80"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  employee:
    build:
      context: .
      dockerfile: Nsu.Contest.Web.Employee/Dockerfile
    command: dotnet run
    depends_on:
      hrmanager:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - contest_network

  junior-1:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 1
        EmployeeServiceOptions__EmployeeType: junior

  junior-2:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 2
        EmployeeServiceOptions__EmployeeType: junior

  junior-3:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 3
        EmployeeServiceOptions__EmployeeType: junior

  junior-4:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 4
        EmployeeServiceOptions__EmployeeType: junior

  junior-5:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 5
        EmployeeServiceOptions__EmployeeType: junior

  teamlead-1:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 6
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-2:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 7
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-3:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 8
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-4:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 9
        EmployeeServiceOptions__EmployeeType: teamlead

  teamlead-5:
    extends:
      service: employee
    environment:
        EmployeeServiceOptions__EmployeeId: 10
        EmployeeServiceOptions__EmployeeType: teamlead

networks: 
  networks:
  contest_network:
    driver: bridge
  
