FROM mcr.microsoft.com/dotnet/sdk:9.0 AS builder

WORKDIR /app

COPY . ./

COPY migrate.sh /usr/local/bin/migrate.sh
COPY healthcheck.sh /usr/local/bin/healthcheck.sh
RUN chmod +x /usr/local/bin/migrate.sh /usr/local/bin/healthcheck.sh

ENTRYPOINT ["/bin/sh"]
